### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by s7relok** [kalliope-project/kalliope_neuron_gmail#1]
Hi, I have this error after configuring this neuron

> Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/RestAPI/utils.py", line 33, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/RestAPI/FlaskAPI.py", line 178, in run_synapse_by_name
    response = lifo_buffer.execute(is_api_call=True, no_voice=no_voice)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/LIFOBuffer.py", line 111, in execute
    cls._process_synapse_list(last_synapse_fifo_list)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/LIFOBuffer.py", line 139, in _process_synapse_list
    cls._process_neuron_list(matched_synapse=matched_synapse)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/LIFOBuffer.py", line 176, in _process_neuron_list
    parameters_dict=matched_synapse.parameters)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/NeuronLauncher.py", line 57, in start_neuron
    instantiated_neuron = NeuronLauncher.launch_neuron(neuron)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/NeuronLauncher.py", line 40, in launch_neuron
    resources_dir=neuron_folder)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/Utils/Utils.py", line 140, in get_dynamic_class_instantiation
    return klass(**parameters)
  File "/home/tommy/kalliope_starter_fr/resources/neurons/gmail_checker/gmail_checker.py", line 40, in __init__
    email.fetch()
  File "/usr/local/lib/python2.7/dist-packages/gmail/message.py", line 159, in fetch
    self.parse(results[0])
  File "/usr/local/lib/python2.7/dist-packages/gmail/message.py", line 144, in parse
    self.sent_at = datetime.datetime.fromtimestamp(time.mktime(email.utils.parsedate_tz(self.message['date'])[:9]))
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/RestAPI/utils.py", line 33, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/RestAPI/FlaskAPI.py", line 178, in run_synapse_by_name
    response = lifo_buffer.execute(is_api_call=True, no_voice=no_voice)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/LIFOBuffer.py", line 111, in execute
    cls._process_synapse_list(last_synapse_fifo_list)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/LIFOBuffer.py", line 139, in _process_synapse_list
    cls._process_neuron_list(matched_synapse=matched_synapse)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/LIFOBuffer.py", line 176, in _process_neuron_list
    parameters_dict=matched_synapse.parameters)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/NeuronLauncher.py", line 57, in start_neuron
    instantiated_neuron = NeuronLauncher.launch_neuron(neuron)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/NeuronLauncher.py", line 40, in launch_neuron
    resources_dir=neuron_folder)
  File "/usr/local/lib/python2.7/dist-packages/kalliope/core/Utils/Utils.py", line 140, in get_dynamic_class_instantiation
    return klass(**parameters)
  File "/home/tommy/kalliope_starter_fr/resources/neurons/gmail_checker/gmail_checker.py", line 40, in __init__
    email.fetch()
  File "/usr/local/lib/python2.7/dist-packages/gmail/message.py", line 159, in fetch
    self.parse(results[0])
  File "/usr/local/lib/python2.7/dist-packages/gmail/message.py", line 144, in parse
    self.sent_at = datetime.datetime.fromtimestamp(time.mktime(email.utils.parsedate_tz(self.message['date'])[:9]))
TypeError: 'NoneType' object has no attribute '__getitem__

> 

my brain file : 

```yml
 
 - name: "check-email"
   signals:
     - order: "est-ce que j'ai des emails?"
     - order: "quels sont mes emails?"
     - order: "j'ai des emails?"
   neurons:
     - gmail_checker:
         username: "myuserwithoutatgmaildotcom"
         password: "mypassword"
         file_template: "templates/gmail.j2"

```

Can you help? Thanks in advance

**Comment by Sispheor** [comment]
The error is in the gmail lib.
Did you setup your gmail account to allow third party app to access it?

**Comment by s7relok** [comment]
Yes, it's configured

**Comment by Sispheor** [comment]
I just tried from my side and the neuron works well.
You haven't received an error from google server in you email?
I think the app is not authorized.

**Comment by s7relok** [comment]
No such mail  in the box.
Is there a particular format for the username? Is @gmail.com mandatory or it can work only with the username?

**Comment by Sispheor** [comment]
Yes it's with @gmail.com

**Comment by Sispheor** [comment]
There is an example in the doc
```yml

- name: "check-email"
  signals:
    - order: "Do I have emails"
  neurons:
    - gmail_checker:
        username: "me@gmail.com"
        password: "my_password"
        say_template: 
          -  "You have {{ unread }} new emails"

```

**Comment by s7relok** [comment]
Ok, that's maybe why this is not working. I will try with full email adress

**Comment by s7relok** [comment]
Changed, but no luck. Same output

**Comment by s7relok** [comment]
I have the same problem with the same output with our without @gmail.com
Account is connfigured to allow "less secure" connections
I have no mail about an app which tries to connect. 

In fact, it seems that kalliope faults before sending something. Can someone help? 
I can provide some file extracts, tell me what.

**Comment by Sispheor** [comment]
Do you have an error?
Kalliope stop working? can you run it with `--debug` flag?
Can you show us the used synapse and template?
Thx.

**Comment by Sispheor** [comment]
No news since one year. I close this one.
