### ISSUE TITLE
brain problem on gmail

### ISSUE THREAD

**Issue by Amrxl** [kalliope-project/kalliope_neuron_gmail#2]
i've installed gamil on kallioipe but when i run kalliope it wont start it gives me

DEBUG:kalliope:[LIFOBuffer] LIFO buffer created
Traceback (most recent call last):
  File "/usr/local/bin/kalliope", line 11, in <module>
    load_entry_point('kalliope==0.5.2', 'console_scripts', 'kalliope')()
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/__init__.py", line 136, in main
    brain_loader = BrainLoader(file_path=brain_file)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/Models/Singleton.py", line 6, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/ConfigurationManager/BrainLoader.py", line 44, in __init__
    self.yaml_config = self.get_yaml_config()
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/ConfigurationManager/BrainLoader.py", line 62, in get_yaml_config
    return YAMLLoader.get_config(brain_file_path)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/ConfigurationManager/YAMLLoader.py", line 54, in get_config
    inc_import = IncludeImport(cls.file_path_to_load)
  File "/usr/local/lib/python2.7/dist-packages/kalliope-0.5.2-py2.7.egg/kalliope/core/ConfigurationManager/YAMLLoader.py", line 91, in __init__
    self.update(yaml.load(f))
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "/home/pi/kalliope_starter_en/brains/gmail_checker.yml", line 2, column 3
expected <block end>, but found '<block mapping start>'
  in "/home/pi/kalliope_starter_en/brains/gmail_checker.yml", line 3, column 5

i think i have a problem in my brain file
this is what i have in the brain file ...
```yml
---
- name: "check-email"
    signals:
      - order: "Do I have emails"
    neurons:
      - gmail_checker:
          username: ""
          password: ""
          file_template: /templates/my_email_template.j2
```
@Sispheor

**Comment by Sispheor** [comment]
Indentation error.

**Comment by Sispheor** [comment]
Also if you start your path with a smash it becomes absolute and not relative. So /templates is not right I think.
